### ISSUE TITLE
Feature request: Support Made for GoogleCardBoard QRCodes to set viewer params

### ISSUE THREAD

**Issue by PixelPartner** [Aralekk/VR_Toolkit_iOS#1]
In your README you stated "Supports all VR viewers". But all have sligtly different optical parameters.

Do you plan to put more efforts into VR? Then it might be worth to add
- Scanning and decoding QR codes
- Looking up the shortened URLs
- decode the content with protobuf
- refactor to use the new MDLStereoscopicCamera class in MetalKit
- adopt to the iOS device / LCD size
- set FOV, IOD and distortion accordingly

**Comment by Aralekk** [comment]
Hi,

I'm going to commit the option to play Stereoscopic (top/bottom) video today.
Thanks for the tip I will look into it, MDLStereoscopicCamera looks great.

:)

Arthur

**Comment by Aralekk** [comment]
NB: I'll commit the stereoscopic video to this project: https://github.com/Aralekk/simple360player_iOS and look at the MDLStereoscopicCamera for both
